language: python

python:
 - 2.7

before_install:
 - wget https://github.com/mozilla/rhino/releases/download/Rhino1_7_8_Release/rhino-1.7.8.zip
 - unzip rhino-1.7.8.zip -d /tmp
 - mkdir -p javascript/rhino/buildGradle/libs
 - cp /tmp/rhino1.7.8/lib/rhino-1.7.8.jar javascript/rhino/buildGradle/libs
 - ls javascript/rhino/buildGradle/libs

install:
 - pip install tox-travis 

script:
 - tox

notifications:
  email:
    recipients:
      # - ci-notifications@myorg.org
    on_success: always
    on_failure: always